# Contact SauSAliens on the plugin page if you need help.
# Plugin page: http://bit.ly/1SMxY8S

Version: 1

#####################################################
#                                                   #
#    Configurations & Enabling/Disabling effects    #
#                                                   #
#####################################################

# Remove their transformation when they teleport via command or plugin.
Teleportation_Removal: true

# This true or false the lightning effect when transforming.
Lightning_Effect: true

# This true or false the explosion effect when transforming
Explosion_Effect: true

# If the Explosion_Effect is set to "true", then you have the option to make blocks around you explode_normal when transforming.
# (Leave "0" if you just want the effect).
Explosion_Radius: 3

# This true or false the sound when transforming (Sound: Ghast Firing)
Sound_Effect: true

# How many action points do you want the player to have when they first start? (Default is 10)
Starting_Action_Points: 10

# How many stat points a player will start with. This sets all attributes such as health, attack, defence, etc... (default is 5)
Starting_Stat_Points: 5

# Action Points from kills configuration
Action_Points_Rewards:
  # Player kill rewards
  Player_Kills:
    Base_Reward: 5  # Base AP for any player kill
    Level_Bonus: 2  # Additional AP per level difference (when killing higher level players)
  
  # Mob kill rewards
  Mob_Kills:
    Boss_Mobs:  # Ender Dragon, Wither
      Reward: 25
    Strong_Mobs:  # Elder Guardian, Warden, Ravager
      Reward: 15
    Medium_Strong_Mobs:  # Blaze, Witch, Vindicator, Piglin Brute, Iron Golem
      Reward: 10
    Medium_Mobs:  # Zombie, Skeleton, Spider, Creeper, Enderman, Piglin
      Reward: 5
    Weak_Mobs:  # Passive animals
      Reward: 1
    Default_Reward: 2  # For any unlisted mob

# The multiplier for every player's Battle Power. (Default is 2)
Base_Battle_Power_Multiplier: 2

# The non-passive (When they hold the charge item) multiplier for every player's energy gain (Default is 2)
NGain_Energy_Multiplier: 2

# The passive multiplier (How much energy they gain over time) for every player's energy gain (Default is 1)
PGain_Energy_Multiplier: 1

# The multiplier for every player's energy limit (Default is 100)
Energy_Multiplier_Limit: 100

# Hold the charge item or click the charge button to gain energy.
Hold_Charge_Item: true

# Passive or active energy gain.
Passive_Energy_Gain: false

# Enables the max stats limit.
Max_Stats_Limit: false

# Limits the stats to a max of what you set here if you have "Max_Stats" set to "true".
Max_Stats: 1000

# Maximum level for Saiyan abilities
Max_Ability_Level: 400