# Contact Mitchell on the plugin page if you need help.
# Plugin page: http://bit.ly/1SMxY8S

Version: 1

#####################################################
#                                                   #
#    Configurations & Enabling/Disabling effects    #
#                                                   #
#####################################################

# The prefix when the plugin send you a message.
Prefix: "&c[&bSuper Saiyan PL&c] "

# Remove their transformation when they teleport via command or plugin.
Teleportation_Removal: true

# This true or false the lightning effect when transforming.
Lightning_Effect: true

# This true or false the explosion effect when transforming
Explosion_Effect: true

# If the Explosion_Effect is set to "true", then you have the option to make blocks around you expload_normal when transforming.
# (Leave "0" if you just want the effect).
Explosion_Radious: 0

# This true or false the sound when transforming (Sound: Ghast Firing)
Sound_Effect: True

# How many action points do you want the player to have when they first start? (Default is 10)
Starting_Action_Points: 10

# How many attribute points a player will start with. This sets all attributes such as health, attack, defence, etc... (default is 5)
Starting_Attribute_Points: 5